name: MineCore
version: 1.0.0
main: me.squishyslime.minecore.Main
description: An utility plugin designed to ease the managing of a Minecraft server.
author: SquishySlime
website: https://skwaraa.online
api-version: '1.21'

commands:
  fly:
    description: Gives you the ability to fly.
  vanish:
    description: Allows you to hide from other players.
  pickup:
    description: Allows you to disable/enable picking up items.
  invsee:
    description: Allows you to see another player's inventory.
  balance:
    description: Allows you to check your or another player's balance.
    aliases:
      - bal
      - money
  eco:
    description: Allows you to change another player's balance.
  gm:
    description: Allows you to change your or another player's gamemode.
    aliases:
      - gamemode
  heal:
    description: Allows you to heal.
  feed:
    description: Allows you to feed.
  repair:
    description: Allows you to repair all the items in your inventory.
  workbench:
    description: Allows you to open the crafting bench.
    aliases:
      - wb
  enderchest:
    description: Allows you to open your enderchest.
    aliases:
      - ec
  god:
    description: Allows you to turn on/off god mode!